/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nfhsnetwork.unitytool.ui.components;

import com.nfhsnetwork.unitytool.utils.LocalFileHelper;
import com.nfhsnetwork.unitytool.utils.UserUtils;

import javax.swing.TransferHandler;

/**
 *
 * @author calebbrandt
 */
public class IDLabel extends javax.swing.JPanel {

    private String id;
    private String url;
    
    /**
     * Creates new form IDLabel
     */
    public IDLabel() {
        initComponents();
    }
    
    public IDLabel(final String id, final String url) {
        initComponents();
        set(id, url);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_id = new javax.swing.JLabel();
        b_copy = new javax.swing.JButton();
        b_goto = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(12, 17));
        setPreferredSize(new java.awt.Dimension(163, 17));

        l_id.setText("gam1234567890");
        l_id.setMaximumSize(new java.awt.Dimension(1123, 17));

        b_copy.setIcon(LocalFileHelper.Assets.getIconForComponent(b_copy, "copy.png"));
        b_copy.setMaximumSize(new java.awt.Dimension(23, 23));
        b_copy.setMinimumSize(new java.awt.Dimension(23, 23));
        b_copy.setPreferredSize(new java.awt.Dimension(23, 23));
        b_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_copyActionPerformed(evt);
            }
        });

        b_goto.setIcon(LocalFileHelper.Assets.getIconForComponent(b_goto, "externallink.png"));
        b_goto.setMaximumSize(new java.awt.Dimension(23, 23));
        b_goto.setMinimumSize(new java.awt.Dimension(23, 23));
        b_goto.setPreferredSize(new java.awt.Dimension(23, 23));
        b_goto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_gotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(l_id, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_goto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_goto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_copyActionPerformed
        UserUtils.Transfer.copyToClipboard(id);
    }//GEN-LAST:event_b_copyActionPerformed

    private void b_gotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_gotoActionPerformed
        UserUtils.openInBrowser(url);
    }//GEN-LAST:event_b_gotoActionPerformed
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_copy;
    private javax.swing.JButton b_goto;
    private javax.swing.JLabel l_id;
    // End of variables declaration//GEN-END:variables

    public void set(final String id, final String url) {
        l_id.setText(id);
        this.id = id;
        this.url = url;
        this.repaint();
    }
}
