/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nfhsnetwork.calebsunitytool.ui;

/**
 *
 * @author Caleb Brandt
 */

class MainWindowBak2 extends javax.swing.JFrame {

    /**
     * Creates new form EventDetailsPane
     */
    public MainWindowBak2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginDialog = new javax.swing.JDialog();
        tf_emailField = new com.nfhsnetwork.calebsunitytool.ui.components.PlaceholderTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        panel_main = new javax.swing.JPanel();
        container_eventSpecific = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        eventDetailsPane1 = new com.nfhsnetwork.calebsunitytool.ui.EventDetailsPane();
        productionTabPane1 = new com.nfhsnetwork.calebsunitytool.ui.ProductionTabPane();
        pixellotTabPane1 = new com.nfhsnetwork.calebsunitytool.ui.PixellotTabPane();
        panel_title = new javax.swing.JPanel();
        label_gameTitle = new javax.swing.JLabel();
        gameListContainer2 = new com.nfhsnetwork.calebsunitytool.ui.GameListContainer();
        mb_topMenu = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menuItem_refresh = new javax.swing.JMenuItem();
        menuItem_importNewData = new javax.swing.JMenuItem();
        menuItem_openPixellotCSV = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItem_exportToFocus = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();
        menuItemCB_enableEditing = new javax.swing.JCheckBoxMenuItem();
        menu_view = new javax.swing.JMenu();
        menu_subView_gameList = new javax.swing.JMenu();
        view_gameList_eventID = new javax.swing.JRadioButtonMenuItem();
        view_gameList_bdcID = new javax.swing.JRadioButtonMenuItem();
        view_gameList_title = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jPasswordField1.setText("jPasswordField1");

        tf_emailField.setPlaceholder("Email Address");

        javax.swing.GroupLayout loginDialogLayout = new javax.swing.GroupLayout(loginDialog.getContentPane());
        loginDialog.getContentPane().setLayout(loginDialogLayout);
        loginDialogLayout.setHorizontalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDialogLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tf_emailField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );
        loginDialogLayout.setVerticalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tf_emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unity Tool - by Caleb Brandt");
        setLocationByPlatform(true);
        setName("UnityToolWindow"); // NOI18N
        setResizable(false);

        tabPanel.addTab("Event", eventDetailsPane1);
        tabPanel.addTab("Production", productionTabPane1);
        pixellotTabPane1.setVisible(true);
        tabPanel.addTab("Pixellot", pixellotTabPane1);

        panel_title.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));
        panel_title.setDoubleBuffered(false);
        panel_title.setFocusable(false);
        panel_title.setRequestFocusEnabled(false);
        panel_title.setVerifyInputWhenFocusTarget(false);

        label_gameTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        label_gameTitle.setText("Varsity Football | Loyola Academy vs. St. Rita High School");

        javax.swing.GroupLayout panel_titleLayout = new javax.swing.GroupLayout(panel_title);
        panel_title.setLayout(panel_titleLayout);
        panel_titleLayout.setHorizontalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(label_gameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_titleLayout.setVerticalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(label_gameTitle)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout container_eventSpecificLayout = new javax.swing.GroupLayout(container_eventSpecific);
        container_eventSpecific.setLayout(container_eventSpecificLayout);
        container_eventSpecificLayout.setHorizontalGroup(
            container_eventSpecificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_eventSpecificLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(container_eventSpecificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container_eventSpecificLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tabPanel))
                    .addComponent(panel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        container_eventSpecificLayout.setVerticalGroup(
            container_eventSpecificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_eventSpecificLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(panel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabPanel))
        );

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mainLayout.createSequentialGroup()
                .addComponent(gameListContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(container_eventSpecific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container_eventSpecific, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gameListContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu_file.setText("File");

        menuItem_refresh.setText("Refresh Data");
        menu_file.add(menuItem_refresh);

        menuItem_importNewData.setText("Import New Data");
        menu_file.add(menuItem_importNewData);

        menuItem_openPixellotCSV.setText("Import Pixellot CSV");
        menu_file.add(menuItem_openPixellotCSV);
        menu_file.add(jSeparator1);

        menuItem_exportToFocus.setText("Export as Focus List Sheet");
        menu_file.add(menuItem_exportToFocus);

        mb_topMenu.add(menu_file);

        menu_edit.setText("Edit");

        menuItemCB_enableEditing.setText("Enable Editing");
        menu_edit.add(menuItemCB_enableEditing);

        mb_topMenu.add(menu_edit);

        menu_view.setText("View");

        menu_subView_gameList.setText("Game List");

        view_gameList_eventID.setSelected(true);
        view_gameList_eventID.setText("Event ID");
        menu_subView_gameList.add(view_gameList_eventID);

        view_gameList_bdcID.setSelected(true);
        view_gameList_bdcID.setText("Broadcast ID");
        menu_subView_gameList.add(view_gameList_bdcID);

        view_gameList_title.setSelected(true);
        view_gameList_title.setText("Title");
        menu_subView_gameList.add(view_gameList_title);

        menu_view.add(menu_subView_gameList);

        jMenu1.setText("jMenu1");
        menu_view.add(jMenu1);

        mb_topMenu.add(menu_view);

        setJMenuBar(mb_topMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_bdcID_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bdcID_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bdcID_fieldActionPerformed

    private void ed_l_redirect_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed_l_redirect_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ed_l_redirect_dataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container_eventSpecific;
    private com.nfhsnetwork.calebsunitytool.ui.EventDetailsPane eventDetailsPane1;
    private com.nfhsnetwork.calebsunitytool.ui.GameListContainer gameListContainer2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel label_gameTitle;
    private javax.swing.JDialog loginDialog;
    private javax.swing.JMenuBar mb_topMenu;
    private javax.swing.JCheckBoxMenuItem menuItemCB_enableEditing;
    private javax.swing.JMenuItem menuItem_exportToFocus;
    private javax.swing.JMenuItem menuItem_importNewData;
    private javax.swing.JMenuItem menuItem_openPixellotCSV;
    private javax.swing.JMenuItem menuItem_refresh;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_subView_gameList;
    private javax.swing.JMenu menu_view;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_title;
    private com.nfhsnetwork.calebsunitytool.ui.PixellotTabPane pixellotTabPane1;
    private com.nfhsnetwork.calebsunitytool.ui.ProductionTabPane productionTabPane1;
    private javax.swing.JTabbedPane tabPanel;
    private com.nfhsnetwork.calebsunitytool.ui.components.PlaceholderTextField tf_emailField;
    private javax.swing.JRadioButtonMenuItem view_gameList_bdcID;
    private javax.swing.JRadioButtonMenuItem view_gameList_eventID;
    private javax.swing.JRadioButtonMenuItem view_gameList_title;
    // End of variables declaration//GEN-END:variables
	
                   

	@SuppressWarnings("unused")
    static class MainWindowFields
    {
		private static String gender;
		private static String prodType;
		private static String onairstatus;
		
		
    	
    	private static String ed_level;
    	private static String ed_participant1;
    	private static String ed_participant2;
    	private static String ed_participant3;
    	private static String ed_participant4;
    	private static String ed_sport;
    	private static String ed_type;
    	private static String ed_location;
    	private static String ed_redirect;
    	private static String ed_startTime;
    	private static String ed_bdcID;
    	
    	private static String pxl_status;
    	private static String pxl_lminame;
    	private static String pxl_clubname;
    	private static String pxl_sfname;
    	private static String pxl_currentCal;
    	private static String pxl_acctmgr;
    	private static String pxl_clubeventurl;
    	private static String pxl_clubsystemurl;
    	private static String pxl_clubeventstatus;
    	private static String pxl_clubeventid;
    	
    	private static String prod_hlsstatus;
    	private static String prod_producer;
    	private static String prod_publisher;
    	private static String prod_mgr_name;
    	private static String prod_mgr_phone;
    	private static String prod_focustype;
    	
    	private static String prod_monitoring_;
    	//TODO figure out monitoring details
    	// can get from STATS json
    	
    	//TODO make setters that also change the respective labels
    	
    	void setGender(String s)
    	{
    		gender = s;
    	}
    	
    }
}
	
    

    

    
    

